# Configuration for CI test with custom target: TestHandleEvent/Successful_Deployment_with_custom_Target
name: compose-webhook
repository_url: https://github.com/kimdre/doco-cd_tests.git # Deployment target is remote repository