version: "2"
linters:
  default: standard
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - errname
    - gosec
    - misspell
    - nilerr
    - unconvert
    - godot
    - gocritic
    - makezero
    - perfsprint
    - wsl_v5
    - revive
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: defer
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        #- name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unhandled-error
          arguments: # Disable for these only
            - fmt.Printf
            - fmt.Print
            - fmt.Println
            - io.Writer.Write
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
          arguments:
            # Custom Allowlist
            - ["ID", "HTTP", "URL", "API"]
            # Custom  Blocklist
            - []
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    #    gofmt:
    #      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/kimdre/doco-cd
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  timeout: 5m
