coverage:
  status:
    project:
      default:
        # Lower the project-wide coverage target so the overall check is easier to reach
        target: auto
        # Allow small negative/positive swings before failing (percent)
        threshold: 5%
    patch:
      default:
        # Set the patch (PR) target to 0% so PRs won't fail due to coverage deltas
        target: auto
        threshold: 5%
