x-poll-config: &poll-config
  POLL_CONFIG: |
    - url: https://github.com/kimdre/doco-cd_tests.git
      reference: secret-provider
      interval: 10
      target: ""

services:
  app:
    container_name: doco-cd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=dev
    restart: unless-stopped
    depends_on:
      - proxy
#      - apprise
    ports:
      - "80:80"
      - "9120:9120"
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: info
      # DOCKER_API_VERSION: 1.47
      <<: *poll-config
      #POLL_CONFIG_FILE: /poll.yml
      HTTP_PROXY: http://username:password@proxy:8888
#      APPRISE_API_URL: http://apprise:8000/notify
#      APPRISE_NOTIFY_LEVEL: info
      # APPRISE_NOTIFY_URLS: # .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
#    secrets:
#      - source: docker-config
#        target: /root/.docker/config.json
#    configs: # Use with POLL_CONFIG_FILE
#      - source: poll.yml
#        target: /poll.yml

  proxy:
    image: vimagick/tinyproxy:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      TZ: Europe/Berlin
    configs:
      - source: tinyproxy.conf
        target: /etc/tinyproxy/tinyproxy.conf

#  apprise:
#    image: caronc/apprise:latest
#    restart: unless-stopped
#    ports:
#      - "8000:8000"
#    environment:
#      TZ: Europe/Berlin
#      APPRISE_WORKER_COUNT: 1

volumes:
  data:

#secrets:
#  docker-config:
#    file: docker-config.json

configs:
  poll.yml:
    content: |
      - url: https://example.com
        branch: main
      - url: https://other-example.com
        interval: 120
      - url: https://yet-another-example.com
        branch: dev
  tinyproxy.conf:
    content: |
      # https://tinyproxy.github.io/
      LogLevel Warning
      Port 8888
      Timeout 600
      BasicAuth username password