x-poll-config: &poll-config
  POLL_CONFIG: |
    - url: https://github.com/kimdre/doco-cd_tests.git
      #url: git@github.com:kimdre/doco-cd_tests.git
      reference: main
      interval: 10
      #target: "bitwarden-sm"

services:
  app:
    container_name: doco-cd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=dev
    pull_policy: build
    restart: unless-stopped
    depends_on:
      proxy:
        condition: "service_started"
      apprise:
        condition: "service_started"
        required: false
    ports:
      - "80:80"
      - "9120:9120"
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: debug
      # DOCKER_API_VERSION: 1.47
      <<: *poll-config
      #POLL_CONFIG_FILE: /poll.yml
      #HTTP_PROXY: http://username:password@proxy:8888
      #SSH_PRIVATE_KEY_FILE: /run/secrets/ssh-private-key
#      APPRISE_API_URL: http://apprise:8000/notify
#      APPRISE_NOTIFY_LEVEL: info
      # APPRISE_NOTIFY_URLS: # .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
#    secrets:
#      - ssh-private-key
#      - source: docker-config
#        target: /root/.docker/config.json
#    configs: # Use with POLL_CONFIG_FILE
#      - source: poll.yml
#        target: /poll.yml

  proxy:
    image: vimagick/tinyproxy:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      TZ: Europe/Berlin
    configs:
      - source: tinyproxy.conf
        target: /etc/tinyproxy/tinyproxy.conf

  apprise:
    profiles:
      - notifications
    image: caronc/apprise:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      TZ: Europe/Berlin
      APPRISE_WORKER_COUNT: 1

  grafana:
    # Dashboard: https://github.com/kimdre/doco-cd/discussions/583
    profiles:
      - monitoring
    image: grafana/grafana:12.3.0
    restart: unless-stopped
    user: "1000"
    ports:
      - "3300:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      TZ: Europe/Berlin

  prometheus:
    depends_on:
      - app
    profiles:
      - monitoring
    restart: unless-stopped
    image: prom/prometheus:v3.8.0
    ports:
      - "9090:9090"
    volumes:
#      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    configs:
      - source: prometheus.yaml
        target: /etc/prometheus/prometheus.yaml
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.size=100MB
      - --storage.tsdb.wal-compression
    environment:
      TZ: Europe/Berlin

volumes:
  data:
  prometheus-data:
  grafana-data:

#secrets:
#  ssh-private-key:
#    file: ./ed25519
#  docker-config:
#    file: docker-config.json

configs:
  poll.yml:
    content: |
      - url: https://example.com
        branch: main
      - url: https://other-example.com
        interval: 120
      - url: https://yet-another-example.com
        branch: dev
  tinyproxy.conf:
    content: |
      # https://tinyproxy.github.io/
      LogLevel Warning
      Port 8888
      Timeout 600
      BasicAuth username password
  prometheus.yaml:
    content: |
      global:
        scrape_interval: 10s

      scrape_configs:
        - job_name: doco-cd
          static_configs:
            - targets: ['doco-cd:9120']