x-poll-config: &poll-config
  POLL_CONFIG: |
    - url: https://github.com/kimdre/doco-cd.git
      reference: main
      interval: 15
      target: "" # "test"
      private: true

services:
  app:
    container_name: doco-cd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=dev
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: info
      # DOCKER_API_VERSION: 1.47
      <<: *poll-config
      #POLL_CONFIG_FILE: /poll.yml
      HTTP_PROXY: http://username:password@proxy:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
#    configs: # Use with POLL_CONFIG_FILE
#      - source: poll.yml
#        target: /poll.yml

  proxy:
    image: vimagick/tinyproxy:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      TZ: Europe/Berlin
    configs:
      - source: tinyproxy.conf
        target: /etc/tinyproxy/tinyproxy.conf

volumes:
  data:

configs:
  poll.yml:
    content: |
      - url: https://example.com
        branch: main
      - url: https://other-example.com
        interval: 120
      - url: https://yet-another-example.com
        branch: dev
  tinyproxy.conf:
    content: |
      # https://tinyproxy.github.io/
      LogLevel Connect
      Port 8888
      Timeout 600
      BasicAuth username password