services:
  app:
    container_name: doco-cd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=dev
    restart: no
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: debug
      # DOCKER_API_VERSION: 1.47
    # The connection to the docker socket requires the user to be either root
    # or in the docker group (the group id may vary and needs to match the docker socket permissions)
    # Use `user: root` to run the app as root, or use `group_add` to use the non-root user and add the docker group id to it
    #user: root
    group_add:
      - "971"  # change to the docker group id shown in the app error logs or in the output of `ls -l /var/run/docker.sock`
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
