# NOTE: This is just for testing deployments
services:
  app:
    container_name: doco-cd
    image: nginx:latest
    environment:
      test: true
    ports:
      - "80:80"
    volumes:
      - test:/var/www/html

volumes:
  test: