# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]
site_name = "Doco-CD Documentation"
site_description = "Doco-CD is a lightweight, declarative GitOps continuous delivery tool for Docker and Docker Swarm"
site_author = "doco-cd contributors"
site_url = "https://doco.cd/"
copyright = "&copy; 2026 Doco-CD Contributors"
repo_url = "https://github.com/kimdre/doco-cd"
repo_name = "kimdre/doco-cd"
edit_uri = "edit/main/wiki/docs/"

docs_dir = "docs"
site_dir = "site"

nav = [
  { Home = "index.md" },
  { "Getting Started" = [
    { "Getting Started" = "Getting-Started.md" },
    { "Setup Access Token" = "Setup-Access-Token.md" },
    { "Setup SSH Key" = "Setup-SSH-Key.md" },
    { "Setup Webhook" = "Setup-Webhook.md" }
  ] },
  { Configuration = [
    { "App Settings" = "App-Settings.md" },
    { "Deploy Settings" = "Deploy-Settings.md" },
    { "Poll Settings" = "Poll-Settings.md" },
  ] },
  { Advanced = [
    { "Swarm Mode" = "Advanced/Swarm-Mode.md" },
    { "Private Container Registries" = "Advanced/Private-Container-Registries.md" },
    { Encryption = "Advanced/Encryption.md" },
    { "External Secrets" = [
      "External-Secrets/index.md",
      { "AWS Secrets Manager" = "External-Secrets/AWS-Secrets-Manager.md" },
      { "Bitwarden Secrets Manager" = "External-Secrets/Bitwarden-Secrets-Manager.md" },
      { "Bitwarden Vault / Vaultwarden" = "External-Secrets/Bitwarden-Vault-Vaultwarden.md" },
      { "1Password" = "External-Secrets/1Password.md" },
      { Infisical = "External-Secrets/Infisical.md" },
      { OpenBao = "External-Secrets/Openbao.md" },
      { Webhook = "External-Secrets/Webhook.md" }] },
    { Notifications = "Advanced/Notifications.md" },
    { "Pre- / Post-Deployment Scripts" = "Advanced/Pre-Post-Deployment-Scripts.md" },
    { "Tips & Tricks" = "Advanced/Tips-and-Tricks.md" }
  ] },
  { Reference = [
    { "Core Concepts" = "Core-Concepts.md" },
    { Endpoints = [
      { "Prometheus Metrics / Monitoring" = "Endpoints/Metrics.md" },
      { "REST API" = "Endpoints/REST-API.md" },
      { "Webhook Listener" = "Endpoints/Webhook-Listener.md" },
    ] },
    { "Known Limitations" = "Known-Limitations.md" },
    { "Contributing" = "Contributing.md" },
    { "Documentation" = "wiki/" },
    { "Security Policy" = "Security.md" },
    { "License" = "License.md" },
  ] },
  { Releases = "https://github.com/kimdre/doco-cd/releases" },
  { "Status" = "https://github.com/users/kimdre/projects/3/views/1" }
]

extra_javascript = [
  "https://unpkg.com/tablesort@5.7.1/dist/tablesort.min.js",
  "javascripts/tablesort.js"
]
extra_css = [
  "stylesheets/extra.css",
  "stylesheets/navigation.css"
]

[project.theme]
language = "en"
logo = "images/doco-cd_containers.svg"
favicon = "images/doco-cd_containers.svg"
features = [
  "content.action.edit",
  "content.action.view",
  "content.code.select",
  "content.code.copy",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "toc.follow",
  "search.highlight",
  "search.suggest",
  "search.share",
]
custom_dir = "overrides"

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/solid/heart"
link = "https://github.com/sponsors/kimdre"
name = "Support this project"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/kimdre/doco-cd"
name = "Github"

[project.extra.version]
provider = "mike"
default = "latest"
alias = true

[project.extra.analytics]
provider = "custom"
scriptSrc = "https://tracking.maki-it.de/api/script.js"
siteId = "d92a5c3f266b"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.tables]
[project.markdown_extensions.toc]
permalink = true

# pymdownx
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.snippets]

# zensical
[project.markdown_extensions.zensical.extensions.preview]
configurations = [
  { targets.include = [
    "*"
  ] }
]