// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: secretprovider/v1/secretprovider.proto

package secretproviderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretProvider_Info_FullMethodName                    = "/secretprovider.v1.SecretProvider/Info"
	SecretProvider_GetSecrets_FullMethodName              = "/secretprovider.v1.SecretProvider/GetSecrets"
	SecretProvider_ResolveSecretReferences_FullMethodName = "/secretprovider.v1.SecretProvider/ResolveSecretReferences"
)

// SecretProviderClient is the client API for SecretProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretProvider is the plugin interface for retrieving secret values from
// an external backend.
type SecretProviderClient interface {
	// Info returns the provider's identifier and version.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// GetSecrets retrieves one or more secret values in a single call.
	GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error)
	// ResolveSecretReferences resolves a map of environment-variable names to
	// secret references, returning the resolved values keyed by the same
	// environment-variable names.
	ResolveSecretReferences(ctx context.Context, in *ResolveSecretReferencesRequest, opts ...grpc.CallOption) (*ResolveSecretReferencesResponse, error)
}

type secretProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretProviderClient(cc grpc.ClientConnInterface) SecretProviderClient {
	return &secretProviderClient{cc}
}

func (c *secretProviderClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, SecretProvider_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretProviderClient) GetSecrets(ctx context.Context, in *GetSecretsRequest, opts ...grpc.CallOption) (*GetSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretsResponse)
	err := c.cc.Invoke(ctx, SecretProvider_GetSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretProviderClient) ResolveSecretReferences(ctx context.Context, in *ResolveSecretReferencesRequest, opts ...grpc.CallOption) (*ResolveSecretReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretReferencesResponse)
	err := c.cc.Invoke(ctx, SecretProvider_ResolveSecretReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretProviderServer is the server API for SecretProvider service.
// All implementations must embed UnimplementedSecretProviderServer
// for forward compatibility.
//
// SecretProvider is the plugin interface for retrieving secret values from
// an external backend.
type SecretProviderServer interface {
	// Info returns the provider's identifier and version.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// GetSecrets retrieves one or more secret values in a single call.
	GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error)
	// ResolveSecretReferences resolves a map of environment-variable names to
	// secret references, returning the resolved values keyed by the same
	// environment-variable names.
	ResolveSecretReferences(context.Context, *ResolveSecretReferencesRequest) (*ResolveSecretReferencesResponse, error)
	mustEmbedUnimplementedSecretProviderServer()
}

// UnimplementedSecretProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretProviderServer struct{}

func (UnimplementedSecretProviderServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSecretProviderServer) GetSecrets(context.Context, *GetSecretsRequest) (*GetSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecrets not implemented")
}
func (UnimplementedSecretProviderServer) ResolveSecretReferences(context.Context, *ResolveSecretReferencesRequest) (*ResolveSecretReferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecretReferences not implemented")
}
func (UnimplementedSecretProviderServer) mustEmbedUnimplementedSecretProviderServer() {}
func (UnimplementedSecretProviderServer) testEmbeddedByValue()                        {}

// UnsafeSecretProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretProviderServer will
// result in compilation errors.
type UnsafeSecretProviderServer interface {
	mustEmbedUnimplementedSecretProviderServer()
}

func RegisterSecretProviderServer(s grpc.ServiceRegistrar, srv SecretProviderServer) {
	// If the following call panics, it indicates UnimplementedSecretProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretProvider_ServiceDesc, srv)
}

func _SecretProvider_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretProviderServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretProvider_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretProviderServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretProvider_GetSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretProviderServer).GetSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretProvider_GetSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretProviderServer).GetSecrets(ctx, req.(*GetSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretProvider_ResolveSecretReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretProviderServer).ResolveSecretReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretProvider_ResolveSecretReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretProviderServer).ResolveSecretReferences(ctx, req.(*ResolveSecretReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretProvider_ServiceDesc is the grpc.ServiceDesc for SecretProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secretprovider.v1.SecretProvider",
	HandlerType: (*SecretProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _SecretProvider_Info_Handler,
		},
		{
			MethodName: "GetSecrets",
			Handler:    _SecretProvider_GetSecrets_Handler,
		},
		{
			MethodName: "ResolveSecretReferences",
			Handler:    _SecretProvider_ResolveSecretReferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secretprovider/v1/secretprovider.proto",
}
