name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  DOCS_BRANCH: gh-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install docs requirements
        run: pip install -r ./wiki/requirements.txt

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "docs-deploy@doco.cd"

      - name: Publish dev docs
        run: mike deploy --branch $DOCS_BRANCH --config-file ./wiki/zensical.toml --allow-empty --push next

      - name: Publish release docs
        if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          MAJOR_MINOR="$(echo $VERSION | sed -E 's/^(v[0-9]+\.[0-9]+)\..*$/\1/')"

          mike deploy --branch $DOCS_BRANCH --config-file ./wiki/zensical.toml --push --allow-empty --update-aliases "$MAJOR_MINOR" latest
          mike set-default --branch $DOCS_BRANCH --config-file ./wiki/zensical.toml --allow-empty --push latest

  deploy:
    name: Deploy to GitHub Pages
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout published docs branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ env.DOCS_BRANCH }}

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          # Upload entire repository
          path: '.'
          include-hidden-files: true
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5

