name: Housekeeping

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  image-cleanup:
    name: Cleanup Container Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: cleanup-images
    steps:
      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1
        with:
          keep-n-untagged: 10
      - name: Delete old release candidate images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1
        with:
          delete-tags: '*-rc*'
          keep-n-tagged: 3